sudo: required
services:
  - docker

before_install:
  - docker build -t adeluleye/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run adeluleye/react-test npm run test -- --coverage

after_success:
  - docker build -t adeluleye/mc-client ./client
  - docker build -t adeluleye/mc-nginx ./nginx
  - docker build -t adeluleye/mc-server ./server
  - docker build -t adeluleye/mc-worker ./worker
  # Log in to the docker CLI, always set variables in the travis project dashboard
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push adeluleye/mc-client
  - docker push adeluleye/mc-nginx
  - docker push adeluleye/mc-server
  - docker push adeluleye/mc-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: mc-docker-react
  env: McDockerReact-env
  bucket_name: elasticbeanstalk-us-west-2-656822776663
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
